# Generated by Django 4.2.1 on 2023-06-02 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0004_remove_reply_is_like_reply_reply_content"),
    ]

    operations = [
        migrations.RemoveField(model_name="feed", name="like_count",),
    ]
